id = "october"
name = "October CMS"
version = "0.3.5"
schema_version = 1
authors = ["Devin Green <artistro08@users.noreply.github.com>"]
description = "Syntax highlighting for October CMS templates in Zed"
repository = "https://github.com/artistro08/zed-october"

[grammars.october]
repository = "https://github.com/artistro08/tree-sitter-october"
rev = "62c69c26d70d0f544ac908ba9b49d6498f0a73ba"
