id = "october"
name = "October CMS"
version = "0.3.7"
schema_version = 1
authors = ["Devin Green <artistro08@users.noreply.github.com>"]
description = "Syntax highlighting for October CMS templates in Zed"
repository = "https://github.com/artistro08/zed-october"

[grammars.october]
repository = "https://github.com/artistro08/tree-sitter-october"
rev = "77d27b5c94e2826c930fde14165daca2e67c3f7c"
