id = "october"
name = "October CMS"
version = "0.4.1"
schema_version = 1
authors = ["Devin Green <artistro08@users.noreply.github.com>"]
description = "Syntax highlighting for October CMS templates in Zed"
repository = "https://github.com/artistro08/zed-october"

[grammars.october]
repository = "https://github.com/artistro08/tree-sitter-october"
rev = "b6fd5f7c82b9830795e386a4908c29778e54f55b"
