id = "october"
name = "October CMS"
version = "0.7.0"
schema_version = 1
authors = ["Devin Green <artistro08@users.noreply.github.com>"]
description = "Syntax highlighting for October CMS templates in Zed"
repository = "https://github.com/artistro08/zed-october"

[grammars.october]
repository = "https://github.com/artistro08/tree-sitter-october"
rev = "509e9d9da723d518b0496e8ddc7714ec8ea535be"

[grammars.ini]
repository = "https://github.com/justinmk/tree-sitter-ini"
rev = "e4018b5176132b4f3c5d6e61cea383f42288d0f5"
