id = "october"
name = "October CMS"
version = "0.2.1"
schema_version = 1
authors = ["Devin Green <artistro08@users.noreply.github.com>"]
description = "Syntax highlighting for October CMS templates in Zed"
repository = "https://github.com/artistro08/zed-october"

[grammars.october]
repository = "https://github.com/artistro08/tree-sitter-october"
rev = "597074fde11a7e355874473c096705b446edbab0"
