name = "October CMS"
grammar = "october"
path_suffixes = ["htm"]
autoclose_before = "}])>"
block_comment = ["{# ", " #}"]
brackets = [
    { start = "{{", end = "}}", close = true, newline = true },
    { start = "{%", end = "%}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "<", end = ">", close = true, newline = true, not_in = [
        "comment",
        "string",
    ] },
    { start = "!--", end = " --", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]
word_characters = ["-"]
